In [1]:
%matplotlib inline


什么是PyTorch？
================

PyTorch是一个基于Python的科学计算包，它主要有两个用途：

-  类似Numpy但是能利用GPU加速
-  一个非常灵活和快速的用于深度学习的研究平台

入门
---------------

Tensor
^^^^^^^

Tensor类似与NumPy的ndarray，但是可以用GPU加速。



In [2]:
from __future__ import print_function
import torch

构造一个5x3的矩阵，未初始化：


In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-8.9602e+25,  4.5560e-41,  1.2859e-37],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 6.8322e-07,  2.1027e+20, -6.3528e-11]])


构造一个随机初始化的矩阵：


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7708, 0.9620, 0.0062],
        [0.6762, 0.8512, 0.3808],
        [0.1306, 0.0090, 0.2810],
        [0.4013, 0.2433, 0.8295],
        [0.4082, 0.4299, 0.7848]])


构造一个用零初始化的矩阵，它的类型(dtype)是long：



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


使用Python的数组来构造Tensor：


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


从已有的tensor信息(size和dtype)来构造tensor。我们也可以用不同的dtype来构造。




In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.4145,  2.3707, -1.2691],
        [-0.5762,  0.3905, -0.7635],
        [-0.3051,  0.2491, -0.7909],
        [-0.6256, -1.6052,  1.2538],
        [ 1.0184,  0.4827,  1.4783]])


查看它的size



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>注意</h4><p>``torch.Size``其实是一个tuple，因此它支持所有的tuple操作</p></div>

Operation
^^^^^^^^^^
同一个operation可能有多种语法。下面是第一种使用加法的语法：



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9843,  2.5384, -0.9066],
        [-0.2077,  0.9302, -0.7118],
        [ 0.0234,  1.1288, -0.7171],
        [-0.0322, -0.9226,  2.1789],
        [ 1.4417,  0.5709,  2.4731]])


使用加法的第二种语法：



In [10]:
print(torch.add(x, y))

tensor([[-0.9843,  2.5384, -0.9066],
        [-0.2077,  0.9302, -0.7118],
        [ 0.0234,  1.1288, -0.7171],
        [-0.0322, -0.9226,  2.1789],
        [ 1.4417,  0.5709,  2.4731]])


给加法提供返回值(而不是生成一个新的返回值)：


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9843,  2.5384, -0.9066],
        [-0.2077,  0.9302, -0.7118],
        [ 0.0234,  1.1288, -0.7171],
        [-0.0322, -0.9226,  2.1789],
        [ 1.4417,  0.5709,  2.4731]])


就地运算的加法(把x加到y上，直接修改y)：



In [12]:
# 把x加到y
y.add_(x)
print(y)

tensor([[-0.9843,  2.5384, -0.9066],
        [-0.2077,  0.9302, -0.7118],
        [ 0.0234,  1.1288, -0.7171],
        [-0.0322, -0.9226,  2.1789],
        [ 1.4417,  0.5709,  2.4731]])


<div class="alert alert-info"><h4>注意</h4><p>所有就地修改一个tensor的operation都会以下划线结尾。
    比如： ``x.copy_(y)``, ``x.t_()``, 都会修改``x``.</p></div>

我们也可以使用类似numpy的下标运算：


In [13]:
print(x[:, 1])

tensor([ 2.3707,  0.3905,  0.2491, -1.6052,  0.4827])


如果想resize或者reshape一个Tensor，我们可以使用``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1的意思是让PyTorch自己推断出第一维的大小。
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果一个tensor只有一个元素，可以使用``.item()``来把它变成一个Python number



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3835])
0.3834681808948517


**深入阅读:**
 
  `这里 <http://pytorch.org/docs/torch>`的文档描述了上百个Tensor的运算，包括转置，索引，slicing，数学运算，线性代收，随机数等等。

与NumPy数组的转换
------------

Torch Tensor和NumPy数组的转换非常容易。

它们会共享内存地址，因此修改一方会影响另一方。

把一个Torch Tensor转换成NumPy数组
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


我们修改一个会影响另外一个。


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


把NumPy数组转成Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CPU上的所有类型的Tensor(除了CharTensor)都可以和Numpy数组来回转换。


CUDA Tensor
------------

Tensor可以使用``.to``方法来移到任意设备上。



In [20]:
# 如果有CUDA
# 我们会使用``torch.device``来把tensors放到GPU上
if torch.cuda.is_available():
    device = torch.device("cuda")          # 一个CUDA device对象。
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 也可以使用``.to("cuda")``把一个tensor从CPU移到GPU上
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to``也可以在移动的过程中修改dtype

tensor([1.3835], device='cuda:0')
tensor([1.3835], dtype=torch.float64)
